parameters:
    app.mercure.topic.base: '%env(MERCURE_PUBLIC_URL)%/instances/%env(MERCURE_TOPIC_NAMESPACE)%'

mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish:
                    - '%app.mercure.topic.base%/users/{userId}/notifications'
                    - '%app.mercure.topic.base%/focus'
