# Attribute routes: legacy Module/Controller and DDD Module/Presentation/Controller
controllers:
    resource:
        path: ../src/
        namespace: App
    type: attribute

api_login_check:
    path: /api/login_check
