<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705014907 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acte_medical (id INT AUTO_INCREMENT NOT NULL, consultation_id INT NOT NULL, type VARCHAR(255) NOT NULL, dent VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, prix DOUBLE PRECISION NOT NULL, quantite INT NOT NULL, INDEX IDX_8EF3CE7662FF6CDF (consultation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE allergy (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, libelle VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_CBB142B56B899279 (patient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE antecedent (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, description VARCHAR(255) DEFAULT NULL, date_enregistrement DATETIME NOT NULL, type VARCHAR(55) DEFAULT NULL, INDEX IDX_3166BE7C6B899279 (patient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_setting (id INT AUTO_INCREMENT NOT NULL, key_name VARCHAR(120) NOT NULL, value JSON NOT NULL COMMENT \'(DC2Type:json)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX uniq_app_setting_key (key_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appreciation (id INT AUTO_INCREMENT NOT NULL, patient_id INT DEFAULT NULL, consultation_id INT DEFAULT NULL, rating SMALLINT NOT NULL, comment LONGTEXT NOT NULL, is_anonymous TINYINT(1) DEFAULT 0 NOT NULL, is_published TINYINT(1) DEFAULT 1 NOT NULL, author_name VARCHAR(255) DEFAULT NULL, author_email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_5CD4DEAB6B899279 (patient_id), UNIQUE INDEX uniq_appreciation_consultation (consultation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assurance (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(64) DEFAULT NULL, actif TINYINT(1) DEFAULT 1 NOT NULL, notes LONGTEXT DEFAULT NULL, taux_par_defaut DOUBLE PRECISION DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, logo_path VARCHAR(255) DEFAULT NULL, form_schema JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking (id INT AUTO_INCREMENT NOT NULL, begin_at DATETIME NOT NULL, end_at DATETIME DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, statut INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE charge_fixe (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(150) NOT NULL, montant NUMERIC(10, 0) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE conge (id INT AUTO_INCREMENT NOT NULL, employe_id INT NOT NULL, type VARCHAR(50) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_2ED893481B65292 (employe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consommable (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, quantity INT NOT NULL, fournisseur VARCHAR(255) DEFAULT NULL, low_value INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, fiche_medicale_id INT DEFAULT NULL, medecin_id INT DEFAULT NULL, infirmier_id INT DEFAULT NULL, salle_id INT DEFAULT NULL, note_seance LONGTEXT DEFAULT NULL, type VARCHAR(50) DEFAULT NULL, statut INT NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_964685A66B899279 (patient_id), INDEX IDX_964685A69A99F4BC (fiche_medicale_id), INDEX IDX_964685A64F31A84 (medecin_id), INDEX IDX_964685A6C2BE0752 (infirmier_id), INDEX IDX_964685A6DC304035 (salle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_urgence (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, nom VARCHAR(255) NOT NULL, lien_parente VARCHAR(50) NOT NULL, telephone VARCHAR(20) NOT NULL, UNIQUE INDEX UNIQ_E9524A4C6B899279 (patient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contenu_devis (id INT AUTO_INCREMENT NOT NULL, devis_id INT NOT NULL, designation VARCHAR(255) NOT NULL, qte INT NOT NULL, montant DOUBLE PRECISION NOT NULL, montant_total DOUBLE PRECISION NOT NULL, INDEX IDX_C6939A4D41DEFADA (devis_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devis (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT DEFAULT NULL, date DATETIME NOT NULL, montant DOUBLE PRECISION DEFAULT NULL, reste DOUBLE PRECISION DEFAULT NULL, statut INT DEFAULT NULL, type INT NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_8B27C52B9A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employe (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, telephone VARCHAR(255) DEFAULT NULL, fonction VARCHAR(255) NOT NULL, date_embauche DATE NOT NULL, coming_days_in_week JSON NOT NULL COMMENT \'(DC2Type:json)\', is_on_days_off TINYINT(1) NOT NULL, type_salaire VARCHAR(255) NOT NULL, valeur_salaire NUMERIC(10, 2) DEFAULT NULL, frequence_paiement VARCHAR(32) DEFAULT \'mensuel\' NOT NULL, type_prime VARCHAR(32) DEFAULT \'aucune\' NOT NULL, valeur_prime NUMERIC(10, 2) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, matricule VARCHAR(100) DEFAULT NULL, type_contrat VARCHAR(100) NOT NULL, duree_contrat INT DEFAULT NULL, administrative_files JSON NOT NULL COMMENT \'(DC2Type:json)\', type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F804D3B9E7927C74 (email), UNIQUE INDEX UNIQ_F804D3B912B2DC9C (matricule), UNIQUE INDEX UNIQ_F804D3B9A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture (id INT AUTO_INCREMENT NOT NULL, consultation_id INT NOT NULL, date_facture DATETIME NOT NULL, is_reglee TINYINT(1) DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_FE86641062FF6CDF (consultation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_assurance (id INT AUTO_INCREMENT NOT NULL, consultation_id INT NOT NULL, patient_id INT NOT NULL, assurance_id INT NOT NULL, lot_facture_assurance_id INT DEFAULT NULL, coverage_rate DOUBLE PRECISION DEFAULT NULL, consultation_amount DOUBLE PRECISION NOT NULL, is_consultation_payante TINYINT(1) DEFAULT 0 NOT NULL, date_facture DATETIME NOT NULL, insurance_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, is_recouvre TINYINT(1) DEFAULT 0 NOT NULL, assurance_snapshot JSON NOT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_F2C0142A62FF6CDF (consultation_id), INDEX IDX_F2C0142A6B899279 (patient_id), INDEX IDX_F2C0142AB288C3E3 (assurance_id), INDEX IDX_F2C0142A1CFC92C4 (lot_facture_assurance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_bilan (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT NOT NULL, formule_dentaire JSON NOT NULL COMMENT \'(DC2Type:json)\', radiographie_extra_buccale_hypothese LONGTEXT DEFAULT NULL, radiographie_intra_buccale_hypothese LONGTEXT DEFAULT NULL, nfs_detaillee LONGTEXT DEFAULT NULL, tp_tca_inr LONGTEXT DEFAULT NULL, uree LONGTEXT DEFAULT NULL, creatininemie LONGTEXT DEFAULT NULL, glycemie LONGTEXT DEFAULT NULL, diagnostic_positif LONGTEXT DEFAULT NULL, avis_medicales LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_8E5FA57B9A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_document (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT NOT NULL, type VARCHAR(50) NOT NULL, libelle VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, group_key VARCHAR(64) DEFAULT NULL, INDEX IDX_BE77B0E79A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_entretien (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT NOT NULL, motif_consultation LONGTEXT DEFAULT NULL, anamnese LONGTEXT DEFAULT NULL, allaitement TINYINT(1) DEFAULT NULL, grossesse_en_cours TINYINT(1) DEFAULT NULL, menstrues TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_AC366B329A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_entretien_affection (id INT AUTO_INCREMENT NOT NULL, entretien_id INT NOT NULL, nom VARCHAR(150) NOT NULL, est_presente TINYINT(1) DEFAULT NULL, details LONGTEXT DEFAULT NULL, INDEX IDX_269310C548DCEA2 (entretien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_entretien_habitude (id INT AUTO_INCREMENT NOT NULL, entretien_id INT NOT NULL, type VARCHAR(50) NOT NULL, est_presente TINYINT(1) DEFAULT NULL, quantite LONGTEXT DEFAULT NULL, INDEX IDX_16366E7B548DCEA2 (entretien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_entretien_medicament (id INT AUTO_INCREMENT NOT NULL, entretien_id INT NOT NULL, nom VARCHAR(100) NOT NULL, est_utilise TINYINT(1) DEFAULT NULL, details LONGTEXT DEFAULT NULL, INDEX IDX_1FC483548DCEA2 (entretien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_entretien_question (id INT AUTO_INCREMENT NOT NULL, entretien_id INT NOT NULL, question VARCHAR(255) NOT NULL, reponse TINYINT(1) DEFAULT NULL, `precision` LONGTEXT DEFAULT NULL, INDEX IDX_B01C196A548DCEA2 (entretien_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_examen (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT NOT NULL, occlusion VARCHAR(255) DEFAULT NULL, mediane VARCHAR(255) DEFAULT NULL, classes_angle VARCHAR(255) DEFAULT NULL, vestibules VARCHAR(255) DEFAULT NULL, hbd VARCHAR(255) DEFAULT NULL, brossage VARCHAR(255) DEFAULT NULL, soccu VARCHAR(255) DEFAULT NULL, cinematique_mandibulaire VARCHAR(255) DEFAULT NULL, ouverture_buccale VARCHAR(255) DEFAULT NULL, temperature_buccale VARCHAR(255) DEFAULT NULL, amplitude_ouverture VARCHAR(255) DEFAULT NULL, bruits_articulaires VARCHAR(255) DEFAULT NULL, tissus_mous_table JSON NOT NULL COMMENT \'(DC2Type:json)\', tissus_durs_table JSON NOT NULL COMMENT \'(DC2Type:json)\', examen_canaux_excreteurs LONGTEXT DEFAULT NULL, diagnostic_suppose_examens LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_E750223B9A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_examen_item (id INT AUTO_INCREMENT NOT NULL, examen_id INT NOT NULL, categorie VARCHAR(50) NOT NULL, libelle VARCHAR(150) NOT NULL, est_present TINYINT(1) DEFAULT NULL, details LONGTEXT DEFAULT NULL, INDEX IDX_E377F0BC5C8659A (examen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_examen_labo (id INT AUTO_INCREMENT NOT NULL, examen_id INT NOT NULL, type VARCHAR(100) NOT NULL, observation LONGTEXT DEFAULT NULL, resultat LONGTEXT DEFAULT NULL, date_examen DATE DEFAULT NULL, INDEX IDX_6F0B96FE5C8659A (examen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_medicale (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, medecin_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_20D23266B899279 (patient_id), INDEX IDX_20D23264F31A84 (medecin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fiche_plan_traitement (id INT AUTO_INCREMENT NOT NULL, fiche_medicale_id INT NOT NULL, plan_index INT DEFAULT NULL, type VARCHAR(50) NOT NULL, date_supposed DATE DEFAULT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_6A9B8F4E9A99F4BC (fiche_medicale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lot_facture_assurance (id INT AUTO_INCREMENT NOT NULL, assurance_id INT NOT NULL, description VARCHAR(255) DEFAULT NULL, date_debut DATETIME NOT NULL, date_fin DATETIME NOT NULL, statut VARCHAR(20) DEFAULT \'ouvert\' NOT NULL, date_creation DATETIME NOT NULL, date_envoi DATETIME DEFAULT NULL, date_recouvrement DATETIME DEFAULT NULL, notes LONGTEXT DEFAULT NULL, INDEX IDX_8E65E100B288C3E3 (assurance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mode_de_paiement (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, coverage_rate DOUBLE PRECISION DEFAULT NULL, actif TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, emitter_id INT DEFAULT NULL, message LONGTEXT NOT NULL, type VARCHAR(255) NOT NULL, date_envoi DATETIME NOT NULL, etat_vu VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, priority VARCHAR(20) NOT NULL, INDEX IDX_BF5476CA37BC4DC6 (emitter_id), INDEX idx_notification_user (user_id), INDEX idx_notification_date (date_envoi), INDEX idx_notification_state (etat_vu), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ordonnance (id INT AUTO_INCREMENT NOT NULL, consultation_id INT NOT NULL, date DATETIME NOT NULL, medecin_nom VARCHAR(255) DEFAULT NULL, note LONGTEXT DEFAULT NULL, INDEX IDX_924B326C62FF6CDF (consultation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ordonnance_ligne (id INT AUTO_INCREMENT NOT NULL, ordonnance_id INT NOT NULL, designation VARCHAR(255) NOT NULL, posologie VARCHAR(255) DEFAULT NULL, frequence VARCHAR(255) DEFAULT NULL, duree VARCHAR(255) DEFAULT NULL, quantite INT DEFAULT NULL, instructions LONGTEXT DEFAULT NULL, INDEX IDX_CB9DA07A2BF23B8F (ordonnance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement (id INT AUTO_INCREMENT NOT NULL, mode_id INT NOT NULL, consultation_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, date DATETIME NOT NULL, montant DOUBLE PRECISION NOT NULL, INDEX IDX_B1DC7A1E77E5854A (mode_id), UNIQUE INDEX UNIQ_B1DC7A1E62FF6CDF (consultation_id), INDEX IDX_B1DC7A1E7F2DEE08 (facture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patient (id INT AUTO_INCREMENT NOT NULL, derniere_consultation_id INT DEFAULT NULL, portal_user_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naissance DATE DEFAULT NULL, date_inscription DATETIME NOT NULL, sexe VARCHAR(10) NOT NULL, telephone VARCHAR(55) NOT NULL, email VARCHAR(255) DEFAULT NULL, profession VARCHAR(255) DEFAULT NULL, lieu_naissance VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) NOT NULL, num_carnet VARCHAR(50) NOT NULL, groupe_sanguin VARCHAR(5) NOT NULL, referencement VARCHAR(255) NOT NULL, sms_patient_created TINYINT(1) DEFAULT 0 NOT NULL, sms_receipt TINYINT(1) DEFAULT 0 NOT NULL, sms_ticket TINYINT(1) DEFAULT 0 NOT NULL, sms_invoice TINYINT(1) DEFAULT 0 NOT NULL, sms_appointment_reminder TINYINT(1) DEFAULT 0 NOT NULL, sms_unsubscribed TINYINT(1) DEFAULT 0 NOT NULL, sms_blacklisted TINYINT(1) DEFAULT 0 NOT NULL, photo VARCHAR(255) DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, archive_files JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_1ADAD7EBC18BD643 (derniere_consultation_id), UNIQUE INDEX UNIQ_1ADAD7EBA6AB0B8C (portal_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patient_assurance_profile (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, assurance_id INT NOT NULL, coverage_rate DOUBLE PRECISION DEFAULT NULL, form_data JSON NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8EAA61636B899279 (patient_id), INDEX IDX_8EAA6163B288C3E3 (assurance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rdv (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, medecin_id INT DEFAULT NULL, salle_id INT DEFAULT NULL, date_creation DATETIME NOT NULL, date_rdv DATETIME NOT NULL, statut SMALLINT NOT NULL, description VARCHAR(255) NOT NULL, reported_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', duration INT NOT NULL, INDEX IDX_10C31F866B899279 (patient_id), INDEX IDX_10C31F864F31A84 (medecin_id), INDEX IDX_10C31F86DC304035 (salle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salary_payment (id INT AUTO_INCREMENT NOT NULL, employe_id INT NOT NULL, mode_de_paiement_id INT DEFAULT NULL, transaction_id INT DEFAULT NULL, year SMALLINT NOT NULL, month SMALLINT NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, base_amount NUMERIC(12, 2) DEFAULT NULL, salary_type_snapshot VARCHAR(32) NOT NULL, salary_value_snapshot NUMERIC(10, 2) DEFAULT NULL, frequence_snapshot VARCHAR(32) DEFAULT \'mensuel\' NOT NULL, worked_day DATE DEFAULT NULL, prime_type_snapshot VARCHAR(32) DEFAULT \'aucune\' NOT NULL, prime_value_snapshot NUMERIC(10, 2) DEFAULT NULL, base_salary_amount NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, prime_amount NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, calculated_amount NUMERIC(12, 2) NOT NULL, paid_amount NUMERIC(12, 2) NOT NULL, paid_at DATE NOT NULL, note LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_FA2C1EC11B65292 (employe_id), INDEX IDX_FA2C1EC18776F13D (mode_de_paiement_id), INDEX IDX_FA2C1EC12FC0CB0F (transaction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salle (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_log (id INT AUTO_INCREMENT NOT NULL, patient_id INT DEFAULT NULL, phone VARCHAR(64) NOT NULL, message LONGTEXT NOT NULL, status VARCHAR(24) NOT NULL, type VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, provider VARCHAR(32) NOT NULL, provider_message_id VARCHAR(255) DEFAULT NULL, error_message LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A9E43D706B899279 (patient_id), INDEX idx_sms_log_status (status), INDEX idx_sms_log_type (type), INDEX idx_sms_log_created_at (created_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_provider_config (id INT AUTO_INCREMENT NOT NULL, provider VARCHAR(64) NOT NULL, enabled TINYINT(1) NOT NULL, client_id VARCHAR(255) DEFAULT NULL, client_secret_encrypted LONGTEXT DEFAULT NULL, sender_address VARCHAR(255) DEFAULT NULL, sender_name VARCHAR(64) DEFAULT NULL, approved_sender_names JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', patient_preference_bypass JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', base_url VARCHAR(255) NOT NULL, oauth_url VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_queue (id INT AUTO_INCREMENT NOT NULL, patient_id INT DEFAULT NULL, phone VARCHAR(64) NOT NULL, message LONGTEXT NOT NULL, status VARCHAR(24) NOT NULL, retry_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', send_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', sent_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', last_error LONGTEXT DEFAULT NULL, type VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, metadata JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_FD4EA63E6B899279 (patient_id), INDEX idx_sms_queue_status (status), INDEX idx_sms_queue_created_at (created_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_template (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(80) NOT NULL, content LONGTEXT NOT NULL, enabled TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_F1963E8277153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stock (id INT AUTO_INCREMENT NOT NULL, consommable_id INT NOT NULL, employee_id INT DEFAULT NULL, user_id INT NOT NULL, quantite_utilisee INT NOT NULL, date_prise DATETIME NOT NULL, type VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_4B365660C9CEB381 (consommable_id), INDEX IDX_4B3656608C03F15C (employee_id), INDEX IDX_4B365660A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE traitement (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, medecin_id INT NOT NULL, description VARCHAR(255) NOT NULL, date_debut DATETIME NOT NULL, date_fin DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_2A356D276B899279 (patient_id), INDEX IDX_2A356D274F31A84 (medecin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, mode_de_paiement_id INT NOT NULL, facture_id INT DEFAULT NULL, consultation_id INT DEFAULT NULL, paiement_id INT DEFAULT NULL, lot_facture_assurance_id INT DEFAULT NULL, montant NUMERIC(10, 0) NOT NULL, type VARCHAR(20) NOT NULL, description VARCHAR(255) DEFAULT NULL, motif VARCHAR(120) DEFAULT NULL, date_transaction DATETIME NOT NULL, validated TINYINT(1) DEFAULT 0 NOT NULL, validation_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, validation_comment LONGTEXT DEFAULT NULL, validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', rejected_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', role_paiement VARCHAR(32) DEFAULT \'direct\' NOT NULL, taux_prise_en_charge DOUBLE PRECISION DEFAULT NULL, INDEX IDX_723705D18776F13D (mode_de_paiement_id), INDEX IDX_723705D17F2DEE08 (facture_id), INDEX IDX_723705D162FF6CDF (consultation_id), UNIQUE INDEX UNIQ_723705D12A4C4478 (paiement_id), INDEX IDX_723705D11CFC92C4 (lot_facture_assurance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, active TINYINT(1) DEFAULT 1 NOT NULL, notifications_enabled TINYINT(1) DEFAULT 1 NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_device (id INT AUTO_INCREMENT NOT NULL, validated_by_id INT DEFAULT NULL, requested_by_id INT DEFAULT NULL, device_identifier VARCHAR(128) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, custom_name VARCHAR(255) DEFAULT NULL, device_type VARCHAR(80) NOT NULL, user_agent LONGTEXT DEFAULT NULL, ip_address VARCHAR(64) DEFAULT NULL, status VARCHAR(20) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', rejection_reason LONGTEXT DEFAULT NULL, last_seen_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_6C7DADB3C69DE5E5 (validated_by_id), INDEX IDX_6C7DADB34DA1E751 (requested_by_id), INDEX idx_user_device_status (status), UNIQUE INDEX uniq_device_identifier (device_identifier), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_device_access_log (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, device_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, ip_address VARCHAR(64) DEFAULT NULL, user_agent LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_9053CDFDA76ED395 (user_id), INDEX IDX_9053CDFD94A4C7D4 (device_id), INDEX idx_user_device_access_created (created_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE acte_medical ADD CONSTRAINT FK_8EF3CE7662FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE allergy ADD CONSTRAINT FK_CBB142B56B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE antecedent ADD CONSTRAINT FK_3166BE7C6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEAB6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE appreciation ADD CONSTRAINT FK_5CD4DEAB62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED893481B65292 FOREIGN KEY (employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A69A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A6C2BE0752 FOREIGN KEY (infirmier_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A6DC304035 FOREIGN KEY (salle_id) REFERENCES salle (id)');
        $this->addSql('ALTER TABLE contact_urgence ADD CONSTRAINT FK_E9524A4C6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE contenu_devis ADD CONSTRAINT FK_C6939A4D41DEFADA FOREIGN KEY (devis_id) REFERENCES devis (id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B9A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE employe ADD CONSTRAINT FK_F804D3B9A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641062FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facture_assurance ADD CONSTRAINT FK_F2C0142A62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facture_assurance ADD CONSTRAINT FK_F2C0142A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE facture_assurance ADD CONSTRAINT FK_F2C0142AB288C3E3 FOREIGN KEY (assurance_id) REFERENCES assurance (id)');
        $this->addSql('ALTER TABLE facture_assurance ADD CONSTRAINT FK_F2C0142A1CFC92C4 FOREIGN KEY (lot_facture_assurance_id) REFERENCES lot_facture_assurance (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fiche_bilan ADD CONSTRAINT FK_8E5FA57B9A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE fiche_document ADD CONSTRAINT FK_BE77B0E79A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE fiche_entretien ADD CONSTRAINT FK_AC366B329A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE fiche_entretien_affection ADD CONSTRAINT FK_269310C548DCEA2 FOREIGN KEY (entretien_id) REFERENCES fiche_entretien (id)');
        $this->addSql('ALTER TABLE fiche_entretien_habitude ADD CONSTRAINT FK_16366E7B548DCEA2 FOREIGN KEY (entretien_id) REFERENCES fiche_entretien (id)');
        $this->addSql('ALTER TABLE fiche_entretien_medicament ADD CONSTRAINT FK_1FC483548DCEA2 FOREIGN KEY (entretien_id) REFERENCES fiche_entretien (id)');
        $this->addSql('ALTER TABLE fiche_entretien_question ADD CONSTRAINT FK_B01C196A548DCEA2 FOREIGN KEY (entretien_id) REFERENCES fiche_entretien (id)');
        $this->addSql('ALTER TABLE fiche_examen ADD CONSTRAINT FK_E750223B9A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE fiche_examen_item ADD CONSTRAINT FK_E377F0BC5C8659A FOREIGN KEY (examen_id) REFERENCES fiche_examen (id)');
        $this->addSql('ALTER TABLE fiche_examen_labo ADD CONSTRAINT FK_6F0B96FE5C8659A FOREIGN KEY (examen_id) REFERENCES fiche_examen (id)');
        $this->addSql('ALTER TABLE fiche_medicale ADD CONSTRAINT FK_20D23266B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE fiche_medicale ADD CONSTRAINT FK_20D23264F31A84 FOREIGN KEY (medecin_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE fiche_plan_traitement ADD CONSTRAINT FK_6A9B8F4E9A99F4BC FOREIGN KEY (fiche_medicale_id) REFERENCES fiche_medicale (id)');
        $this->addSql('ALTER TABLE lot_facture_assurance ADD CONSTRAINT FK_8E65E100B288C3E3 FOREIGN KEY (assurance_id) REFERENCES assurance (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA37BC4DC6 FOREIGN KEY (emitter_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ordonnance ADD CONSTRAINT FK_924B326C62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE ordonnance_ligne ADD CONSTRAINT FK_CB9DA07A2BF23B8F FOREIGN KEY (ordonnance_id) REFERENCES ordonnance (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E77E5854A FOREIGN KEY (mode_id) REFERENCES mode_de_paiement (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBC18BD643 FOREIGN KEY (derniere_consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBA6AB0B8C FOREIGN KEY (portal_user_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE patient_assurance_profile ADD CONSTRAINT FK_8EAA61636B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE patient_assurance_profile ADD CONSTRAINT FK_8EAA6163B288C3E3 FOREIGN KEY (assurance_id) REFERENCES assurance (id)');
        $this->addSql('ALTER TABLE rdv ADD CONSTRAINT FK_10C31F866B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE rdv ADD CONSTRAINT FK_10C31F864F31A84 FOREIGN KEY (medecin_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE rdv ADD CONSTRAINT FK_10C31F86DC304035 FOREIGN KEY (salle_id) REFERENCES salle (id)');
        $this->addSql('ALTER TABLE salary_payment ADD CONSTRAINT FK_FA2C1EC11B65292 FOREIGN KEY (employe_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE salary_payment ADD CONSTRAINT FK_FA2C1EC18776F13D FOREIGN KEY (mode_de_paiement_id) REFERENCES mode_de_paiement (id)');
        $this->addSql('ALTER TABLE salary_payment ADD CONSTRAINT FK_FA2C1EC12FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sms_log ADD CONSTRAINT FK_A9E43D706B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE sms_queue ADD CONSTRAINT FK_FD4EA63E6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660C9CEB381 FOREIGN KEY (consommable_id) REFERENCES consommable (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656608C03F15C FOREIGN KEY (employee_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE traitement ADD CONSTRAINT FK_2A356D276B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE traitement ADD CONSTRAINT FK_2A356D274F31A84 FOREIGN KEY (medecin_id) REFERENCES employe (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D18776F13D FOREIGN KEY (mode_de_paiement_id) REFERENCES mode_de_paiement (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D17F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D162FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D12A4C4478 FOREIGN KEY (paiement_id) REFERENCES paiement (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D11CFC92C4 FOREIGN KEY (lot_facture_assurance_id) REFERENCES lot_facture_assurance (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB34DA1E751 FOREIGN KEY (requested_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_device_access_log ADD CONSTRAINT FK_9053CDFDA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_device_access_log ADD CONSTRAINT FK_9053CDFD94A4C7D4 FOREIGN KEY (device_id) REFERENCES user_device (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acte_medical DROP FOREIGN KEY FK_8EF3CE7662FF6CDF');
        $this->addSql('ALTER TABLE allergy DROP FOREIGN KEY FK_CBB142B56B899279');
        $this->addSql('ALTER TABLE antecedent DROP FOREIGN KEY FK_3166BE7C6B899279');
        $this->addSql('ALTER TABLE appreciation DROP FOREIGN KEY FK_5CD4DEAB6B899279');
        $this->addSql('ALTER TABLE appreciation DROP FOREIGN KEY FK_5CD4DEAB62FF6CDF');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED893481B65292');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A66B899279');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A69A99F4BC');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A64F31A84');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A6C2BE0752');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A6DC304035');
        $this->addSql('ALTER TABLE contact_urgence DROP FOREIGN KEY FK_E9524A4C6B899279');
        $this->addSql('ALTER TABLE contenu_devis DROP FOREIGN KEY FK_C6939A4D41DEFADA');
        $this->addSql('ALTER TABLE devis DROP FOREIGN KEY FK_8B27C52B9A99F4BC');
        $this->addSql('ALTER TABLE employe DROP FOREIGN KEY FK_F804D3B9A76ED395');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641062FF6CDF');
        $this->addSql('ALTER TABLE facture_assurance DROP FOREIGN KEY FK_F2C0142A62FF6CDF');
        $this->addSql('ALTER TABLE facture_assurance DROP FOREIGN KEY FK_F2C0142A6B899279');
        $this->addSql('ALTER TABLE facture_assurance DROP FOREIGN KEY FK_F2C0142AB288C3E3');
        $this->addSql('ALTER TABLE facture_assurance DROP FOREIGN KEY FK_F2C0142A1CFC92C4');
        $this->addSql('ALTER TABLE fiche_bilan DROP FOREIGN KEY FK_8E5FA57B9A99F4BC');
        $this->addSql('ALTER TABLE fiche_document DROP FOREIGN KEY FK_BE77B0E79A99F4BC');
        $this->addSql('ALTER TABLE fiche_entretien DROP FOREIGN KEY FK_AC366B329A99F4BC');
        $this->addSql('ALTER TABLE fiche_entretien_affection DROP FOREIGN KEY FK_269310C548DCEA2');
        $this->addSql('ALTER TABLE fiche_entretien_habitude DROP FOREIGN KEY FK_16366E7B548DCEA2');
        $this->addSql('ALTER TABLE fiche_entretien_medicament DROP FOREIGN KEY FK_1FC483548DCEA2');
        $this->addSql('ALTER TABLE fiche_entretien_question DROP FOREIGN KEY FK_B01C196A548DCEA2');
        $this->addSql('ALTER TABLE fiche_examen DROP FOREIGN KEY FK_E750223B9A99F4BC');
        $this->addSql('ALTER TABLE fiche_examen_item DROP FOREIGN KEY FK_E377F0BC5C8659A');
        $this->addSql('ALTER TABLE fiche_examen_labo DROP FOREIGN KEY FK_6F0B96FE5C8659A');
        $this->addSql('ALTER TABLE fiche_medicale DROP FOREIGN KEY FK_20D23266B899279');
        $this->addSql('ALTER TABLE fiche_medicale DROP FOREIGN KEY FK_20D23264F31A84');
        $this->addSql('ALTER TABLE fiche_plan_traitement DROP FOREIGN KEY FK_6A9B8F4E9A99F4BC');
        $this->addSql('ALTER TABLE lot_facture_assurance DROP FOREIGN KEY FK_8E65E100B288C3E3');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA37BC4DC6');
        $this->addSql('ALTER TABLE ordonnance DROP FOREIGN KEY FK_924B326C62FF6CDF');
        $this->addSql('ALTER TABLE ordonnance_ligne DROP FOREIGN KEY FK_CB9DA07A2BF23B8F');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E77E5854A');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E62FF6CDF');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E7F2DEE08');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EBC18BD643');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EBA6AB0B8C');
        $this->addSql('ALTER TABLE patient_assurance_profile DROP FOREIGN KEY FK_8EAA61636B899279');
        $this->addSql('ALTER TABLE patient_assurance_profile DROP FOREIGN KEY FK_8EAA6163B288C3E3');
        $this->addSql('ALTER TABLE rdv DROP FOREIGN KEY FK_10C31F866B899279');
        $this->addSql('ALTER TABLE rdv DROP FOREIGN KEY FK_10C31F864F31A84');
        $this->addSql('ALTER TABLE rdv DROP FOREIGN KEY FK_10C31F86DC304035');
        $this->addSql('ALTER TABLE salary_payment DROP FOREIGN KEY FK_FA2C1EC11B65292');
        $this->addSql('ALTER TABLE salary_payment DROP FOREIGN KEY FK_FA2C1EC18776F13D');
        $this->addSql('ALTER TABLE salary_payment DROP FOREIGN KEY FK_FA2C1EC12FC0CB0F');
        $this->addSql('ALTER TABLE sms_log DROP FOREIGN KEY FK_A9E43D706B899279');
        $this->addSql('ALTER TABLE sms_queue DROP FOREIGN KEY FK_FD4EA63E6B899279');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660C9CEB381');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656608C03F15C');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660A76ED395');
        $this->addSql('ALTER TABLE traitement DROP FOREIGN KEY FK_2A356D276B899279');
        $this->addSql('ALTER TABLE traitement DROP FOREIGN KEY FK_2A356D274F31A84');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D18776F13D');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D17F2DEE08');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D162FF6CDF');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D12A4C4478');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D11CFC92C4');
        $this->addSql('ALTER TABLE user_device DROP FOREIGN KEY FK_6C7DADB3C69DE5E5');
        $this->addSql('ALTER TABLE user_device DROP FOREIGN KEY FK_6C7DADB34DA1E751');
        $this->addSql('ALTER TABLE user_device_access_log DROP FOREIGN KEY FK_9053CDFDA76ED395');
        $this->addSql('ALTER TABLE user_device_access_log DROP FOREIGN KEY FK_9053CDFD94A4C7D4');
        $this->addSql('DROP TABLE acte_medical');
        $this->addSql('DROP TABLE allergy');
        $this->addSql('DROP TABLE antecedent');
        $this->addSql('DROP TABLE app_setting');
        $this->addSql('DROP TABLE appreciation');
        $this->addSql('DROP TABLE assurance');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE charge_fixe');
        $this->addSql('DROP TABLE conge');
        $this->addSql('DROP TABLE consommable');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE contact_urgence');
        $this->addSql('DROP TABLE contenu_devis');
        $this->addSql('DROP TABLE devis');
        $this->addSql('DROP TABLE employe');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE facture_assurance');
        $this->addSql('DROP TABLE fiche_bilan');
        $this->addSql('DROP TABLE fiche_document');
        $this->addSql('DROP TABLE fiche_entretien');
        $this->addSql('DROP TABLE fiche_entretien_affection');
        $this->addSql('DROP TABLE fiche_entretien_habitude');
        $this->addSql('DROP TABLE fiche_entretien_medicament');
        $this->addSql('DROP TABLE fiche_entretien_question');
        $this->addSql('DROP TABLE fiche_examen');
        $this->addSql('DROP TABLE fiche_examen_item');
        $this->addSql('DROP TABLE fiche_examen_labo');
        $this->addSql('DROP TABLE fiche_medicale');
        $this->addSql('DROP TABLE fiche_plan_traitement');
        $this->addSql('DROP TABLE lot_facture_assurance');
        $this->addSql('DROP TABLE mode_de_paiement');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE ordonnance');
        $this->addSql('DROP TABLE ordonnance_ligne');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE patient_assurance_profile');
        $this->addSql('DROP TABLE rdv');
        $this->addSql('DROP TABLE salary_payment');
        $this->addSql('DROP TABLE salle');
        $this->addSql('DROP TABLE sms_log');
        $this->addSql('DROP TABLE sms_provider_config');
        $this->addSql('DROP TABLE sms_queue');
        $this->addSql('DROP TABLE sms_template');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE traitement');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_device');
        $this->addSql('DROP TABLE user_device_access_log');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
